# Generated by Django 5.1.1 on 2024-09-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('question', models.TextField(blank=True, null=True)),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=20)),
                ('totalQuestions', models.IntegerField()),
                ('correctAnswers', models.IntegerField()),
                ('scorePercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultDataJSON', models.JSONField()),
                ('recommendedLevel', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=20, null=True)),
                ('resultDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.botuser')),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
    ]
