# Generated by Django 5.1.1 on 2024-09-19 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='resultDate',
        ),
        migrations.AddField(
            model_name='question',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='resultedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
