# Generated by Django 5.1.1 on 2024-09-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_testresult_resultdate_question_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.CharField(max_length=1000, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
