# Generated by Django 5.1.1 on 2024-09-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('telegramId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('telegramContact', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek')], default='uz', max_length=2)),
                ('selectedLevel', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default='beginner', max_length=20)),
                ('confirmedLevel', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default=None, max_length=20, null=True)),
                ('recommendedLevel', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default=None, max_length=20, null=True)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'bot_users',
            },
        ),
    ]
