# Generated by Django 5.0 on 2024-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_botuser_preferred_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
