# Generated by Django 5.0 on 2024-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_botuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('registered', 'Registered'), ('test_taken', 'Test Taken'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Successfully Completed'), ('failed', 'Unsuccessfully Completed')], default='draft', max_length=10),
        ),
    ]
