# Generated by Django 5.0 on 2024-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_botuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='preferred_time_slot',
            field=models.IntegerField(blank=True, choices=[(1, '9:00 to 12:00'), (2, '12:00 to 15:00'), (3, '15:00 to 18:00'), (4, '18:00 to 21:00')], default=1, null=True),
        ),
    ]
