# Generated by Django 5.0 on 2024-10-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_botuser_registeredtype_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='courseType',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], help_text='Choose the type of education that suits you.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='englishLevel',
            field=models.CharField(blank=True, choices=[('none', 'No knowledge'), ('little', 'A little knowledge'), ('average', 'Average knowledge'), ('good', 'Good (Intermediate and above)')], max_length=20, null=True),
        ),
    ]
