# Generated by Django 5.0 on 2024-10-12 11:53

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_survey_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-user__registeredAt'], 'verbose_name': "So'rovnoma ", 'verbose_name_plural': "So'rovnomalar"},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='registeredType',
            field=models.CharField(blank=True, choices=[('survey', 'Participate in the survey'), ('registration', 'Register for the course')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('quality_teaching', "Sifatli ta'lim va malakali ustozlar bo'lsa"), ('additional_tutor', "Qo'shimcha shug'ullanadigan ikkinchi ustoz bo'lsa"), ('free_materials', 'Oxford tizimidagi kitob va daftarlar bepul berilsa'), ('close_location', "Lokatsiya yaqin bo'lsa"), ('modern_conditions', "Zamonaviy sharoitlarda Oksford tizimida dars o'tilsa"), ('friendly_environment', "Do'stona muhitda hamfikr talabalar bilan o'rganilsa"), ('regular_events', 'Ingliz tilida muntazam tadbirlar va musobaqalar uyushtirilsa'), ('english_only', "Faqat ingliz tilida gaplashiladigan muhit bo'lsa"), ('tours', 'Turistik joylarga ekskursiyalar tashkil qilinsa'), ('study_abroad_support', "Chet elda o'qishga hujjat topshirishga yordam berilsa"), ('affordable_prices', "Narxlari to'g'ri kelsa")], max_length=175, null=True, verbose_name='Sharoitlar'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='considerEnrollment',
            field=models.CharField(blank=True, choices=[('yes', "Men qatnashib ko'rgan bo'lardim"), ('no', "Yo'q, hozircha qiziq emas")], max_length=3, null=True, verbose_name="O'qishni xohlaysizmi?"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='courseNumber',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Kurs raqami'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='courseType',
            field=models.CharField(blank=True, choices=[('offline', "O'quv markazida (oflayn)"), ('online', 'Onlayn')], help_text="O'zingizga mos keladigan ta'lim turini tanlang.", max_length=10, null=True, verbose_name='Kurs turi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='daysPerWeek',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Haftada 1 - 2 kun'), (2, 'Haftada 3 kun'), (3, 'Haftaning barcha kunlari')], null=True, verbose_name='Haftada qancha kun'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='educationDirection',
            field=models.CharField(blank=True, choices=[('software_engineering', 'Dasturiy injiniring'), ('computer_engineering', 'Kompyuter injiniringi'), ('banking', 'Bank ishi'), ('finance_and_financial_technologies', 'Moliya va moliyaviy texnologiyalar'), ('logistics', 'Logistika'), ('economics', 'Iqtisodiyot'), ('accounting', 'Buxgalteriya hisobi'), ('tourism_and_hospitality', 'Turizm va mehmondo’stlik'), ('preschool_education', 'Maktabgacha taʼlim'), ('primary_education', 'Boshlangʻich taʼlim'), ('special_pedagogy', 'Maxsus pedagogika'), ('native_language_and_literature', 'Ona tili va adabiyot'), ('foreign_language_and_literature', 'Xorijiy til va adabiyoti'), ('history', 'Tarix'), ('mathematics', 'Matematika'), ('psychology', 'Psixologiya'), ('architecture', 'Arxitektura'), ('social_work', 'Ijtimoiy ish')], max_length=50, null=True, verbose_name="Ta'lim yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='educationType',
            field=models.CharField(blank=True, choices=[('daytime', 'Kunduzgi'), ('evening', 'Kechki'), ('externally', 'Sirtqi')], max_length=20, null=True, verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='englishGoal',
            field=models.CharField(blank=True, choices=[('career', 'Kelajakda yaxshi karyera qilish'), ('knowledge', "Ingliz tilida ma'lumot topib, bilim olish"), ('abroad', "Chet elda ishlash yoki ta'lim olish"), ('entertainment', "Kino va musiqalarni tushunib ko'rish, inglizlar bilan gaplashish"), ('certificate', 'Magistraturaga kirish uchun sertifikat olish')], max_length=20, null=True, verbose_name="Ingliz tili o'rganish maqsadi"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='englishLevel',
            field=models.CharField(blank=True, choices=[('none', 'Umuman bilmayman'), ('little', 'Ozgina bilaman'), ('average', "O'rtacha bilaman"), ('good', 'Bilimim yaxshi (intermediate va yuqori)')], max_length=20, null=True, verbose_name='Ingliz tili darajasi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='englishProficiency',
            field=models.CharField(blank=True, choices=[('ielts', 'IELTS sertifikatini olmoqchiman'), ('fluent', 'Ingliz tilida ravon gaplashmoqchiman'), ('academic', "Ingliz tilida ilmiy nashrlar va kitoblarni o'qimoqchiman"), ('career', "Karyera qilishim uchun yetarli bo'lsa bo'ldi")], help_text='Ingliz tilini qay darajada bilish siz uchun yetarli?', max_length=20, null=True, verbose_name="O'rganishdan maqsad"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='freeLessonParticipation',
            field=models.CharField(blank=True, choices=[('yes', "Ha, bepul ochiq darsga qatnashib ko'raman"), ('no', "Yo'q, hozircha kerak emas")], help_text='Bepul ochiq darsda qatnashishni xohlaysizmi?', max_length=3, null=True, verbose_name='Bepul ochiq darsga qatnashish'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='importanceRanking',
            field=models.TextField(blank=True, help_text="Quyidagi omillarning ahamiyatini 1-5 tartibda baholang: 1. Sifatli ta'lim va malakali o'qituvchilar, 2. Joylashuv, 3. Zamonaviy sharoitlar va do'stona muhit, 4. Tadbirlar (Kinokun, Speaking klubi, Tanlovlar), 5. Arzon narxlar. Masalan: 3, 2, 1, 5, 4", null=True, verbose_name='Muhimlik tartibi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='learningExperience',
            field=models.CharField(blank=True, choices=[('offline', "O'quv markazida (Oflayn)"), ('online', 'Onlayn platformalarda'), ('self_taught', "Mustaqil o'rganganman"), ('no_experience', "O'rganishga imkoniyatim bo'lmagan")], max_length=20, null=True, verbose_name="O'qish tajribasi"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='obstacles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('no_time', 'Yetarli vaqt ajrata olmaganman'), ('no_qualified_teachers', 'Malakali o‘qituvchilar bo‘lmagan'), ('no_motivation', 'Motivatsiya yetishmagan'), ('too_expensive', "Qimmat bo'lgan"), ('center_too_far', 'O‘quv markazi uzoq bo‘lgan'), ('no_obstacles', "Hech qanday to'sqinlik bo'lmagan")], max_length=85, null=True, verbose_name="To'sqinliklar"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='startLearning_importance',
            field=models.CharField(blank=True, choices=[('start_now', 'Hoziroq boshlashga tayyorman'), ('study_later', "Keyinchalik o'qishim mumkin"), ('self_study', "Mustaqil o'rganmoqchiman"), ('not_needed', 'Menga hozircha ingliz tili kerak emas')], max_length=20, null=True, verbose_name='Ingliz tilini boshlash ahamiyati'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='users.botuser', verbose_name='Foydalanuvchi'),
        ),
    ]
