# Generated by Django 5.0 on 2024-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_survey_options_alter_botuser_registeredtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-registeredAt'], 'verbose_name': 'Foydalanuvchi ', 'verbose_name_plural': 'Bot foydalanuvchilari'},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='confirmedLevel',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default=None, max_length=20, null=True, verbose_name='Tasdiqlangan daraja'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='F.I.Sh.'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek')], default='uz', max_length=2, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='preferred_time_slot',
            field=models.IntegerField(blank=True, choices=[(1, '9:00 dan 12:00 gacha'), (2, '12:00 dan 15:00 gacha'), (3, '15:00 dan 18:00 gacha'), (4, '18:00 dan 21:00 gacha')], default=1, null=True, verbose_name='Afzal vaqt'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='recommendedLevel',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default=None, max_length=20, null=True, verbose_name='Tavsiya etilgan daraja'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='registeredAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt"),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='registeredType',
            field=models.CharField(blank=True, choices=[('survey', 'Participate in the survey'), ('registration', 'Register for the course')], max_length=20, null=True, verbose_name="Ro'yxatdan o'tish turi"),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='selectedLevel',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default=None, max_length=20, null=True, verbose_name='Tanlangan daraja'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('registered', "Ro'yxatdan o'tgan"), ('test_taken', 'Test topshirilgan'), ('accepted', 'Qabul qilingan'), ('rejected', 'Qabul qilinmagan'), ('active', 'Faol'), ('suspended', "To'xtatilgan"), ('completed', 'Muvaffaqiyatli tamomlangan'), ('failed', 'Muvaffaqiyatsiz tamomlangan')], default='draft', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegramContact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram kontakti'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegramId',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
