# Generated by Django 5.0 on 2024-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_botuser_options_alter_botuser_confirmedlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='registeredType',
            field=models.CharField(blank=True, choices=[('survey', "So'rovnomadan o'tish"), ('registration', "Kursga ro'yxatdan o'tish")], max_length=20, null=True, verbose_name="Ro'yxatdan o'tish turi"),
        ),
    ]
