# Generated by Django 5.0 on 2024-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_botuser_registeredtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='FISh'),
        ),
    ]
