# Generated by Django 5.0 on 2024-10-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_botuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='registeredType',
            field=models.CharField(choices=[('survey', "So'rovnomadan o'tish"), ('registration', "Kursga ro'yxatdan o'tish")], default='registration', max_length=20, verbose_name="Ro'yxatdan o'tish turi"),
        ),
    ]
