# Generated by Django 5.1.1 on 2024-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, default='Question does not exist', null=True),
        ),
    ]
