# Generated by Django 4.2 on 2024-09-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_question_a_alter_question_b_alter_question_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
