# Generated by Django 4.2 on 2024-09-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_questionresponse_testsession_delete_testresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
