# Generated by Django 4.2 on 2024-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_testsession_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
