# Generated by Django 5.0 on 2024-10-09 07:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_question_isactive'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
