# Generated by Django 5.0 on 2024-10-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_question_managers'),
        ('users', '0011_alter_botuser_options_alter_botuser_confirmedlevel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='questionresponse',
            options={'ordering': ['-id'], 'verbose_name': 'Savol javobi ', 'verbose_name_plural': 'Savol javoblari'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Test sessiyasi ', 'verbose_name_plural': 'Test sessiyalari'},
        ),
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.CharField(max_length=1000, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.CharField(max_length=1000, verbose_name='Variant B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(max_length=1000, verbose_name='Variant C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Variant D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Javob (a, b, c, d)'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='test_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='tests.testsession', verbose_name='Test sessiyasi'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.botuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Tamomlanganmi?'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamomlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='correctAnswers',
            field=models.IntegerField(default=0, verbose_name="To'g'ri javoblar soni"),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlagan vaqt'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='totalQuestions',
            field=models.IntegerField(default=20, verbose_name='Jami savollar'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.botuser', verbose_name='Foydalanuvchi'),
        ),
    ]
