# Generated by Django 5.0 on 2024-10-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol ', 'verbose_name_plural': 'Savollar'},
        ),
    ]
