# Generated by Django 5.0 on 2024-10-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_question_question'),
        ('tests', '0012_alter_question_options'),
    ]

    operations = [
    ]
