# Generated by Django 5.0 on 2024-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_merge_20241012_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Savol'),
        ),
    ]
