# Generated by Django 5.0 on 2024-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_botuser_registrationdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-registeredAt']},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='selectedLevel',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default=None, max_length=20, null=True),
        ),
    ]
